import type { Category, Product } from "./types";

export const CATEGORIES: Category[] = [
  { name: "Chicken", slug: "chicken", art: "drumstick", tagline: "Tender, juicy, never frozen" },
  { name: "Mutton", slug: "mutton", art: "chops", tagline: "Soft, fresh & flavour-packed" },
  { name: "Seafood", slug: "seafood", art: "prawn", tagline: "Coast-fresh, cleaned & cut" },
  { name: "Eggs", slug: "eggs", art: "eggs", tagline: "Farm eggs, packed daily" },
  { name: "Ready to Cook", slug: "ready-to-cook", art: "kebab", tagline: "Marinated by chefs" },
];

const INR = (amount: number) => ({ amount, currencyCode: "INR" });

const demoVariant = (
  id: string,
  title: string,
  amount: number,
  compareAt: number | null = null,
) => ({
  id: `demo-variant-${id}`,
  title,
  price: INR(amount),
  compareAtPrice: compareAt ? INR(compareAt) : null,
  availableForSale: true,
});

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "demo-1",
    handle: "chicken-curry-cut-skinless",
    title: "Chicken Curry Cut (Skinless)",
    description:
      "The everyday hero. Small, even cuts of bone-in chicken that soak up masala beautifully — perfect for curries, biryani and gravies. Skinned, cleaned and cut after you order.",
    category: "Chicken",
    tags: ["bestseller", "bone-in"],
    badge: "Bestseller",
    weight: "500 g",
    serves: "Serves 3–4",
    pieces: "12–18 pieces",
    image: null,
    art: "curry-cut",
    price: INR(189),
    compareAtPrice: INR(229),
    availableForSale: true,
    variants: [
      demoVariant("1a", "500 g", 189, 229),
      demoVariant("1b", "1 kg", 359, 449),
    ],
  },
  {
    id: "demo-2",
    handle: "chicken-breast-boneless",
    title: "Chicken Breast (Boneless)",
    description:
      "Lean, protein-packed boneless breast fillets. The gym-bag staple — grill it, pan-sear it, or cube it for a stir-fry. Trimmed of fat and cut to an even thickness.",
    category: "Chicken",
    tags: ["protein", "boneless"],
    badge: "High Protein",
    weight: "450 g",
    serves: "Serves 2–3",
    pieces: "2–3 fillets",
    image: null,
    art: "breast",
    price: INR(219),
    compareAtPrice: null,
    availableForSale: true,
    variants: [
      demoVariant("2a", "450 g", 219),
      demoVariant("2b", "900 g", 419),
    ],
  },
  {
    id: "demo-3",
    handle: "chicken-drumsticks",
    title: "Chicken Drumsticks",
    description:
      "Plump, juicy drumsticks with the skin on or off — your call at the kitchen. Made for tandoori nights, sticky glazes and air-fryer experiments.",
    category: "Chicken",
    tags: ["bone-in", "grill"],
    badge: null,
    weight: "6 pieces · ~550 g",
    serves: "Serves 3",
    pieces: "6 pieces",
    image: null,
    art: "drumstick",
    price: INR(179),
    compareAtPrice: null,
    availableForSale: true,
    variants: [demoVariant("3a", "6 pieces", 179), demoVariant("3b", "12 pieces", 339)],
  },
  {
    id: "demo-4",
    handle: "chicken-wings",
    title: "Chicken Wings with Skin",
    description:
      "Crispy-skin potential: 10/10. Whole wings, tip-on, ready for buffalo sauce, pepper-salt fry or a smoky grill. Cleaned and patted dry before packing.",
    category: "Chicken",
    tags: ["grill", "party"],
    badge: "Party Pick",
    weight: "8–10 pieces · ~500 g",
    serves: "Serves 3–4",
    pieces: "8–10 pieces",
    image: null,
    art: "wings",
    price: INR(149),
    compareAtPrice: INR(169),
    availableForSale: true,
    variants: [demoVariant("4a", "500 g", 149, 169)],
  },
  {
    id: "demo-5",
    handle: "whole-chicken-skinless",
    title: "Whole Chicken (Skinless)",
    description:
      "One bird, endless plans. A whole, cleaned, skinless chicken — roast it, butterfly it, or portion it for the week. Giblets removed, neck trimmed.",
    category: "Chicken",
    tags: ["family", "value"],
    badge: null,
    weight: "~1 kg",
    serves: "Serves 4–6",
    pieces: "1 whole bird",
    image: null,
    art: "whole-chicken",
    price: INR(299),
    compareAtPrice: null,
    availableForSale: true,
    variants: [demoVariant("5a", "~1 kg", 299)],
  },
  {
    id: "demo-6",
    handle: "mutton-curry-cut",
    title: "Mutton Curry Cut (Bone-in)",
    description:
      "Tender goat mutton from young, grass-fed animals. Bone-in pieces with just the right fat for a rich, slow-cooked Sunday curry that tastes like home.",
    category: "Mutton",
    tags: ["bestseller", "bone-in"],
    badge: "Bestseller",
    weight: "500 g",
    serves: "Serves 3–4",
    pieces: "10–14 pieces",
    image: null,
    art: "curry-cut",
    price: INR(449),
    compareAtPrice: INR(499),
    availableForSale: true,
    variants: [
      demoVariant("6a", "500 g", 449, 499),
      demoVariant("6b", "1 kg", 869, 999),
    ],
  },
  {
    id: "demo-7",
    handle: "mutton-keema",
    title: "Mutton Keema (Fresh Mince)",
    description:
      "Freshly minced on order — never pre-ground, never frozen. The soul of keema pav, galouti kebabs and stuffed parathas. 80/20 lean-to-fat for maximum flavour.",
    category: "Mutton",
    tags: ["mince"],
    badge: null,
    weight: "500 g",
    serves: "Serves 3–4",
    pieces: "Fresh mince",
    image: null,
    art: "keema",
    price: INR(469),
    compareAtPrice: null,
    availableForSale: true,
    variants: [demoVariant("7a", "500 g", 469)],
  },
  {
    id: "demo-8",
    handle: "mutton-chops",
    title: "Mutton Chops (Rib Cut)",
    description:
      "Frenched rib chops with a delicate fat cap. Pan-sear with garlic and rosemary or marinate overnight for chargha-style chops that fall off the bone.",
    category: "Mutton",
    tags: ["premium", "grill"],
    badge: "Premium",
    weight: "500 g",
    serves: "Serves 2–3",
    pieces: "6–8 chops",
    image: null,
    art: "chops",
    price: INR(549),
    compareAtPrice: null,
    availableForSale: true,
    variants: [demoVariant("8a", "500 g", 549)],
  },
  {
    id: "demo-9",
    handle: "tiger-prawns-cleaned",
    title: "Tiger Prawns (Cleaned & Deveined)",
    description:
      "Big, sweet, snappy tiger prawns — headless, peeled and deveined so you can go straight to the pan. Caught on the coast, on your stove the same week.",
    category: "Seafood",
    tags: ["premium", "cleaned"],
    badge: "Chef's Pick",
    weight: "250 g",
    serves: "Serves 2",
    pieces: "12–16 prawns",
    image: null,
    art: "prawn",
    price: INR(349),
    compareAtPrice: INR(399),
    availableForSale: true,
    variants: [
      demoVariant("9a", "250 g", 349, 399),
      demoVariant("9b", "500 g", 679, 799),
    ],
  },
  {
    id: "demo-10",
    handle: "rohu-curry-cut",
    title: "Rohu Fish (Curry Cut)",
    description:
      "Riverside classic. Fresh rohu cut into curry-ready steaks, descaled and cleaned. Built for mustard gravies, fish fry Fridays and grandma's recipes.",
    category: "Seafood",
    tags: ["bone-in", "river-fish"],
    badge: null,
    weight: "500 g",
    serves: "Serves 3–4",
    pieces: "6–8 steaks",
    image: null,
    art: "fish",
    price: INR(259),
    compareAtPrice: null,
    availableForSale: true,
    variants: [demoVariant("10a", "500 g", 259)],
  },
  {
    id: "demo-11",
    handle: "basa-fillet-boneless",
    title: "Basa Fillet (Boneless)",
    description:
      "Mild, buttery and 100% boneless — the friendliest fish in the sea. Perfect for kids, fish & chips and weeknight pan-fries with zero bone anxiety.",
    category: "Seafood",
    tags: ["boneless", "kids-favourite"],
    badge: "Zero Bones",
    weight: "400 g",
    serves: "Serves 2–3",
    pieces: "2 fillets",
    image: null,
    art: "fillet",
    price: INR(279),
    compareAtPrice: null,
    availableForSale: true,
    variants: [demoVariant("11a", "400 g", 279)],
  },
  {
    id: "demo-12",
    handle: "classic-white-eggs-12",
    title: "Classic White Eggs (12 pack)",
    description:
      "Farm-fresh white eggs collected daily, candled for quality and packed with care. Breakfast, baking, bhurji — the dozen that does it all.",
    category: "Eggs",
    tags: ["daily", "protein"],
    badge: null,
    weight: "12 eggs",
    serves: "12 pieces",
    pieces: "12 eggs",
    image: null,
    art: "eggs",
    price: INR(109),
    compareAtPrice: null,
    availableForSale: true,
    variants: [demoVariant("12a", "12 pack", 109), demoVariant("12b", "30 tray", 249)],
  },
  {
    id: "demo-13",
    handle: "free-range-brown-eggs-6",
    title: "Free Range Brown Eggs (6 pack)",
    description:
      "From hens that actually walk around. Richer yolks, stronger shells, better bhurji. Collected from partner farms every single morning.",
    category: "Eggs",
    tags: ["free-range", "premium"],
    badge: "Free Range",
    weight: "6 eggs",
    serves: "6 pieces",
    pieces: "6 eggs",
    image: null,
    art: "eggs",
    price: INR(89),
    compareAtPrice: null,
    availableForSale: true,
    variants: [demoVariant("13a", "6 pack", 89)],
  },
  {
    id: "demo-14",
    handle: "chicken-tikka-ready",
    title: "Chicken Tikka (Ready to Grill)",
    description:
      "Boneless thigh chunks in our chef's smoky tikka marinade — hung curd, Kashmiri chilli, and 14 spices. Skewer, grill, devour. 15 minutes to glory.",
    category: "Ready to Cook",
    tags: ["marinated", "grill"],
    badge: "Chef's Pick",
    weight: "400 g",
    serves: "Serves 2–3",
    pieces: "14–16 chunks",
    image: null,
    art: "tikka",
    price: INR(249),
    compareAtPrice: INR(289),
    availableForSale: true,
    variants: [demoVariant("14a", "400 g", 249, 289)],
  },
  {
    id: "demo-15",
    handle: "chicken-seekh-kebab",
    title: "Chicken Seekh Kebab",
    description:
      "Hand-rolled seekh kebabs with fresh mince, browned onions, mint and a secret garam masala. Pan, tawa or grill — done in 12 minutes.",
    category: "Ready to Cook",
    tags: ["marinated", "party"],
    badge: null,
    weight: "8 pieces · 400 g",
    serves: "Serves 3–4",
    pieces: "8 kebabs",
    image: null,
    art: "kebab",
    price: INR(229),
    compareAtPrice: null,
    availableForSale: true,
    variants: [demoVariant("15a", "8 pieces", 229)],
  },
  {
    id: "demo-16",
    handle: "chicken-salami-smoked",
    title: "Smoked Chicken Salami",
    description:
      "Thin-sliced, gently smoked chicken salami with no added nitrites. Sandwiches, pizzas and sneaky midnight fridge raids welcome.",
    category: "Ready to Cook",
    tags: ["cold-cuts", "breakfast"],
    badge: "New",
    weight: "200 g",
    serves: "10–12 slices",
    pieces: "10–12 slices",
    image: null,
    art: "salami",
    price: INR(169),
    compareAtPrice: null,
    availableForSale: true,
    variants: [demoVariant("16a", "200 g", 169)],
  },
];

export function demoProductByHandle(handle: string): Product | undefined {
  return DEMO_PRODUCTS.find((p) => p.handle === handle);
}

export function demoProductByVariantId(variantId: string): Product | undefined {
  return DEMO_PRODUCTS.find((p) => p.variants.some((v) => v.id === variantId));
}
